name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Clean previous build cache
        run: rm -rf build
        working-directory: ${{ github.workspace }}

      - name: Configure with CMake
        run: cmake -S . -B build
        working-directory: ${{ github.workspace }}

      - name: Build the project
        run: cmake --build build
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
        working-directory: ${{ github.workspace }}
