name: Build & Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install cmake g++ libgtest-dev

    - name: Configure project
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: ./build/run_tests