 name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Init submodules
        run: git submodule update --init --recursive
        working-directory: ${{ github.workspace }}/tic_tac_toe

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure with CMake
        run: cmake -S . -B build
        working-directory: ${{ github.workspace }}/tic_tac_toe

      - name: Build the project
        run: cmake --build build
        working-directory: ${{ github.workspace }}/tic_tac_toe

       

      - name: Run tests
       run: ctest --output-on-failure
       working-directory: ${{ github.workspace }}/tic_tac_toe/build
  
